apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-operator-rb
  namespace: executor
subjects:
  - kind: ServiceAccount
    name: spark-operator-controller
    namespace: executor
roleRef:
  kind: ClusterRole
  name: spark-operator-role
  apiGroup: rbac.authorization.k8s.io
