apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-cleanup-role
  namespace: default
rules:
- apiGroups: [""]
  resources:
    - pods
    - services
    - configmaps
    - persistentvolumeclaims
  verbs: ["get", "list", "watch", "create", "delete", "deletecollection"]