apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: wordcount-job
  namespace: executor
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: gcr.io/spark-operator/spark-py:v3.1.1
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/scripts/wordcount.py
  sparkVersion: "3.1.1"
  restartPolicy:
    type: Never
  volumes:
    - name: scripts
      configMap:
        name: spark-wordcount
  driver:
    cores: 1
    memory: "512m"
    serviceAccount: spark
    volumeMounts:
      - name: scripts
        mountPath: /opt/spark/scripts
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    volumeMounts:
      - name: scripts
        mountPath: /opt/spark/scripts
